# Generated by Django 2.0.7 on 2018-12-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('rate', models.FloatField()),
                ('title', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=45)),
                ('playable', models.BooleanField()),
                ('cover_x', models.IntegerField()),
                ('cover_y', models.IntegerField()),
                ('cover', models.CharField(max_length=100)),
                ('is_new', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='movieComment',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('movie_id', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='shortComment',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('rate', models.IntegerField()),
                ('movie_id', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
